language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.1.12.0
  - jruby-9.2.13.0
  - jruby-head
  - ruby-head
  - truffleruby
matrix:
  include:
    - rvm: 1.8.7
      dist: trusty
    - rvm: 1.9.2
      dist: trusty
  allow_failures:
    - rvm: jruby-head
    - rvm: jruby-9.0.5.0
    - rvm: ruby-head
    - rvm: truffleruby
gemfile: .travis.gemfile
before_install:
  - gem install bundler || gem install bundler --version '< 2'
