language: ruby
rvm:
  - 1.9.3
  - 2.0.0
matrix:
  include:
    - rvm: 1.8.7
      dist: trusty
    - rvm: 1.9.2
      dist: trusty
gemfile: .ci.gemfile
before_install:
  - gem install bundler --version '< 2'
